Changes three
VolkerJacobsen/quiz-app pull request #7
Opened 2023-05-19 07:21 UTC by VolkerJacobsen

++  updated layout
++ added global and components css files

2023-05-19 12:04 UTC, josch87 requested changes
I made some comments concerning BEM. You could revise all your code with BEM and structure. :)

2023-05-19 12:04 UTC, josch87 commented on css/footer.css
> +.footer_nav {
If you want to add an element to your block, you could use two underlines as a naming convention. Using BEM it would be "footer__nav".

2023-05-19 12:04 UTC, josch87 commented on css/footer.css
> +.navigation {
Is this another element? Then you should put it another component I guess.

2023-05-19 12:04 UTC, josch87 commented on css/footer.css
> +footer .icons {
Using BEM you should not make use of type (or ID) selectors - only classes.

2023-05-19 12:04 UTC, josch87 commented on css/global.css
> +@import "/section.css";
In order to structure your files you could use the following folder schema:
/components/section/section.css

2023-05-19 12:04 UTC, josch87 commented on css/button.css
> +button {
With BEM you could use classes:
.button

2023-05-26 08:03 UTC, NilsOt1 commented on bookmarks.html
> +    <main class="main-content">
Hier fehlt ein Bindestrich in der Benennung der class

2023-05-26 08:05 UTC, NilsOt1 commented on bookmarks.html
> +      <section class="section__bookmark --question1">
Hier hat sich ein Leerzeichen in die class eingeschlichen

2023-05-26 08:07 UTC, NilsOt1 commented on bookmarks.html
> +        <button class="button button--show-answer" type="button">
Hier hat sich ein Leerzeichen in die class eingeschlichen

2023-05-26 08:07 UTC, NilsOt1 commented on bookmarks.html
> +      <section class="section__bookmark --question2">
siehe Zeile 15

2023-05-26 08:09 UTC, NilsOt1 commented on bookmarks.html
> +      <section class="section__bookmark --question3">
siehe Zeile 15

2023-05-26 08:12 UTC, NilsOt1 commented on bookmarks.html
> +      <section class="section__bookmark --question4">
siehe Zeile 15

2023-05-26 08:20 UTC, NilsOt1 commented on profilepage.html
> +        <a class="section__traffic traffic__buttons" class="buttons">
Hier könntest du die Klassen in ein Attribut einfügen, dann brauchst du das nicht zwei Mal

2023-05-26 08:23 UTC, NilsOt1 approved these changes
Mir sind nur ein paar Sachen in den Klassen aufgefallen. Ich glaube es ist bad practice, wenn du in Klassen, in denen du BEM verwendest auch normale Bindestriche verwendest. Schau da noch mal drauf. Ansonsten sieht das echt gut aus! :)

2023-05-26 09:36 UTC, merged